apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-app
  labels:
    app: authentication-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service-app
  template:
    metadata:
      labels:
        app: authentication-service-app
    spec:
      containers:
      - name: authentication-service-app
        image: maritort/authentication-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8086

---
kind: Service
apiVersion: v1
metadata:
  name:  authentication-service-svc
spec:
  selector:
    app:  authentication-service-app
  ports:
  - port:  80
    targetPort:  8086