apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-app
  labels:
    app: client-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service-app
  template:
    metadata:
      labels:
        app: client-service-app
    spec:
      containers:
      - name: client-service-app
        image: maritort/client-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8081

---
kind: Service
apiVersion: v1
metadata:
  name:  client-service-svc
spec:
  selector:
    app:  client-service-app
  ports:
  - port:  80
    targetPort:  8081