apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default  # Reemplaza <NAMESPACE> por el nombre del namespace de tus pods
  name: kafka-access-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default  # Reemplaza <NAMESPACE> por el nombre del namespace de tus pods
  name: kafka-access-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafka-access-role  # Nombre del rol creado en el namespace "kafka"
subjects:
- kind: ServiceAccount
  name: kafka-access-sa  # Nombre de la cuenta de servicio en el namespace actual
  namespace: default  # Reemplaza <NAMESPACE> por el nombre del namespace de tus pods
