apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  #name: zookeeper-service
  namespace: kafka
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    name: zookeeper
  #  - name: zookeeper-port
  #    port: 2181
  #    nodePort: 30181
  #    targetPort: 2181
  #selector:
  #  app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      hostname: zookeeper
      containers:
      - env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
        #- name: ZOOKEEPER_CLIENT_PORT
        #  value: "2181"
        #- name: ZOOKEEPER_TICK_TIME
        #  value: "2000"
        #- name: ZOOKEEPER_INIT_LIMIT
        #  value: "5"
        #- name: ZOOKEEPER_SYNC_LIMIT
        #  value: "2"
        #- name: ZOOKEEPER_SERVER_ID
        #  value: "1"
        #image: wurstmeister/zookeeper
        #imagePullPolicy: IfNotPresent
        #name: zookeeper
        name: zookeeper
        image: digitalwonderland/zookeeper
        ports:
          - containerPort: 2181